---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r include=FALSE}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    snow_mm = snow,
    snow = round(snow_mm * 0.03937 * 4) / 4)
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa %>% 
  filter(month %in% c(11, 12, 1),
         year %in% 2007,
         snow_mm < 100, snow_mm > 0) %>% 
  count(snow_mm) %>% 
  mutate(snow_mm = factor(snow_mm),
         snow_mm = fct_reorder(snow_mm, n)) %>% 
  plot_ly(x = ~snow_mm, y = ~n, color = ~snow_mm,
          type = "bar", colors = "viridis") %>% 
  layout(title = "snow depth counts for November, December and January in 2007")
```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa %>% 
  filter(month %in% c(11, 12, 1),
         year %in% 2007 ) %>% 
  plot_ly(
    x = ~snow_mm, y = ~tmin, 
    alpha = 0.5, type = "scatter", mode = "markers") %>% 
layout(title = "min temp vs. snow depth for Nov, Dec and Jan 2007")
```

### Chart C

```{r}
ny_noaa %>% 
  group_by(month) %>% 
  filter(month %in% c(11, 12),
         year %in% 2007 ) %>% 
  plot_ly(y = ~tmax, x = ~tmin,
          type = "box", colors = "viridis") %>% 
  layout(title = "boxplot of tmax vs. tmin for November and December in 2007")
```

